version: '4'

services:
  main:
    image: drupal:drall
    container_name: drall-main
    build:
      context: .
      dockerfile: .docker/main/Dockerfile
    depends_on:
      - database
    ports:
      - "8080:80"
    volumes:
      - .:/opt/drall
      - .docker/main/sites/sites.php:/opt/drupal/web/sites/sites.php
      - .docker/main/sites/sites.reddish.php:/opt/drupal/web/sites/sites.reddish.php
      - .docker/main/sites/sites.bluish.php:/opt/drupal/web/sites/sites.bluish.php
      - .docker/main/composer.json:/opt/drupal/composer.json
      - .docker/main/drush:/opt/drupal/drush
      - ./Makefile:/opt/drupal/Makefile
    environment:
      - DRALL_ENVIRONMENT=development

  database:
    image: mariadb:10
    container_name: drall-db
    environment:
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
      MARIADB_ROOT_PASSWORD: drupal
    volumes:
      - .docker/database/init.sql:/docker-entrypoint-initdb.d/1-init.sql
