name: validation
on:
  - push
env:
  DRUPAL_PATH: /opt/drupal
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        php-versions: ['8.1']
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Path Setup
        run: |
          echo "/opt/drupal/vendor/bin" >> $GITHUB_PATH
      - name: Determine Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('/opt/*/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Prepare
        run: |
          cp -r . /opt/drall
          make provision
      - name: Info
        run: make info
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Coverage
        run: make coverage-report/text
