name: validation
on:
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Prepare
        run: composer install
      - name: Lint
        run: composer lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2']
    needs:
      - lint
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          docker compose up -d --build --quiet-pull
          docker compose exec -T main make provision
      - name: Test
        run: docker compose exec -T --workdir=/opt/drall -e XDEBUG_MODE=coverage main make test
      - name: Coverage
        run: make coverage-report/text
