name: validation
on:
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Prepare
        run: composer install
      - name: Lint
        run: composer lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0']
    needs:
      - lint
    steps:
      - uses: actions/checkout@v2
      - name: Docker
        run: docker compose build --progress=plain && docker compose up -d
      - name: Prepare
        run: docker compose exec -T main make provision
      - name: Test
        run: docker compose exec -T --workdir=/opt/drall main composer test
      - name: Coverage
        run: make coverage-report/text
